 server:
   port: 8080

 security:
   header:
     prefix: "Bearer "
   jwt:
     secret: "crescer-2018-1-java-jwt"
     expiration: 86400000 # 1 dia em milisegundos
   public:
     path: "/public/**"

 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/email?useTimezone=true&serverTimezone=UTC
     username: root
     password:
   jpa:
     hibernate:
      ddl-auto: update
   jackson:
       serialization:
         write-dates-as-timestamps: false

        