export default {
    HOME: 'HOME',
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    MOSTRARUSUARIO: 'MOSTRARUSUARIO',
    PESQUISARMENSAGENS: 'PESQUISARMENSAGENS',
    PESQUISARUSUARIOS: 'PESQUISARUSUARIOS',
    EDITARPERFIL: 'EDITARPERFIL',
    MENSAGENSENVIADAS: 'MENSAGENSENVIADAS',
    MENSAGENSRECEBIDAS: 'MENSAGENSRECEBIDAS',
    TODASMENSAGENS: 'TODASMENSAGENS'
}